# zookeeper-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper-headless
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:3.8
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
          env:
            - name: ZOO_MY_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name  
          command:
            - sh
            - -c
            - |
              ID=$(echo ${HOSTNAME##*-})
              echo $((ID + 1)) > /data/myid
              cp /conf/zoo.cfg /apache-zookeeper-*/conf/zoo.cfg
              exec zkServer.sh start-foreground
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /conf
      volumes:
        - name: config
          configMap:
            name: zookeeper-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: local-path
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
